#Exoflame blaze burner parameters
[exoflame_parameters]
	#Maximum number of burners exoflame can provide heat to sustainably.
	boost_rate = 9
	#Maximum number of burners exoflame can provide heat to sustainably when superheated.
	seething_boost_rate = 1
