version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
perfectbirbs = true
mcwfences = true
farmersdelight = true
mythicmetals = true
alloy_forgery = true
doapi = true
brewery = true
chimes = true
refurbished_furniture = true
runes = true
friendsandfoes = true
natures_spirit = true
ecologics = true
copycats = false
compact_storage = true
furniture = true
verdantvibes = true
sootychimneys = true
yigd = true
toomanyorigins = true
railways = true
magistuarmory = true
bloomingnature = true
herbalbrews = true
handcrafted = true
thaumon = true
pride_land = true
blocky_bass = true
goodending = true
ftbquests = true
cobblemon = true
halmiscmod = true
spell_engine = true
naturalist = true
botania = true
createbigcannons = true
magnumtorch = true
paladins = true
endrem = true
create = true
yungscavebiomes = true
estrogen = true
biomeswevegone = true
davespotioneering = true
minecraft = true
animal_feeding_trough = true
mcwfurnitures = true
sliceanddice = true
new_soviet = true
valkyrienskies = true
toms_storage = true
candlelight = true
seasonsextras = true
mcwroofs = true
itemcollectors = true
mcwwindows = true
plushables = true
ribbits = true
camping = true
another_furniture = true
dustydecorations = true
diagonalwalls = true
mcwpaths = true
origins = true
things = true
mcwtrpdoors = true
mcwlights = true
milk = true
amendments = true
wilderwild = true
diagonalfences = true
bakery = true
graveyard = true
mca = true
mcwdoors = true
redeco = true
cafesbirding = true
chipped = true
convenientdecor = true
farm_and_charm = true
luphieclutteredmod = true
wildernature = true
trashcans = true
rogues = true
plushies = true
fwaystones = true
createdeco = true
create_bic_bit = true
blahaj = true
perfectplushies = true
nethervinery = true
jewelry = true
beautify = true
immersive_weathering = true
archers = true
diagonalwindows = true
crystal_clear = true
vs_eureka = true
crittersandcompanions = true
vinery = true
gofish = true
enchantinginfuser = true
meadow = true
