version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
candlelight = true
seasonsextras = true
mcwfences = true
farmersdelight = true
mythicmetals = true
mcwroofs = true
itemcollectors = true
alloy_forgery = true
doapi = true
mcwwindows = true
plushables = true
brewery = true
ribbits = true
refurbished_furniture = true
chimes = true
camping = true
ecologics = true
another_furniture = true
friendsandfoes = true
runes = true
natures_spirit = true
copycats = false
compact_storage = true
dustydecorations = true
furniture = true
diagonalwalls = true
verdantvibes = true
mcwlights = true
sootychimneys = true
mcwpaths = true
toomanyorigins = true
herbalbrews = true
origins = true
things = true
mcwtrpdoors = true
magistuarmory = true
bloomingnature = true
diagonalfences = true
milk = true
amendments = true
blocky_bass = true
thaumon = true
handcrafted = true
goodending = true
wilderwild = true
cobblemon = true
halmiscmod = true
bakery = true
graveyard = true
spell_engine = true
mca = true
naturalist = true
mcwdoors = true
cafesbirding = true
botania = true
createbigcannons = true
magnumtorch = true
paladins = true
chipped = true
convenientdecor = true
endrem = true
create = true
farm_and_charm = true
trashcans = true
wildernature = true
luphieclutteredmod = true
plushies = true
biomeswevegone = true
davespotioneering = true
rogues = true
minecraft = true
animal_feeding_trough = true
createdeco = true
mcwfurnitures = true
create_bic_bit = true
blahaj = true
nethervinery = true
sliceanddice = true
jewelry = true
beautify = true
immersive_weathering = true
archers = true
diagonalwindows = true
new_soviet = true
crittersandcompanions = true
crystal_clear = true
vinery = true
gofish = true
enchantinginfuser = true
toms_storage = true
meadow = true
