
["The Garden Awakens"]
	#Determine if creaking hearts should spawn from pale oak saplings
	spawnCreakingHeartsFromSaplings = false
	#Determine if the wandering trader should have trades from the pale garden
	paleTradesFromWanderer = true
	#Determine if Pale Gardens should generate in the overworld
	generatePaleGarden = true
	#Determine if resin should generate after hitting a creaking
	generateResin = true
	#Determine if creakings should spawn from creaking hearts
	spawnCreakingFromHearts = true

